name: HDF_App
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  connectivity: ^0.4.9+3
  device_info: ^0.4.0+1
  ext_storage: ^1.0.3
  firebase_messaging: ^7.0.3
  flutter_launcher_icons: ^0.8.0
  flutter_statusbarcolor: ^0.2.3
  imei_plugin: ^1.0.1
  incrementally_loading_listview: ^0.3.0
  install_plugin: ^2.0.1
  ota_update: ^2.4.1
  package_info: ^0.4.3
  path_provider: ^1.3.1
  permission_handler: ^5.0.1+1
  url_launcher: ^5.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/img/health.png
    - asset/img/report.png
    - asset/img/success.gif
    - asset/img/loading.gif
    - asset/img/loading.svg
    - asset/img/bg.png
    - asset/img/HDF-logo.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: asset/fonts/OpenSans-Regular.ttf
        - asset: asset/fonts/OpenSans-SemiBold.ttf
          weight: 700
        - asset: asset/fonts/OpenSans-ExtraBold.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
